[manager]

prepend_keymap = [
        # New: Open VS Code
  { on = [ "m", "," ], run = 'shell "code ."', desc = "Open VS Code in current directory" },
 # { on = "o", run = "open", desc = "Open selected files" },
  { on = [ "m", "b" ], run = "google-chrome-stable", desc = "Open Google Chrome" },
	{ on = [ "u" ], run = "arrow -7" },
	{ on = [ "i" ], run = "arrow 7" },
  { on = ["g", "u"], run = "cd /mnt/fed/web2", desc = "Go web2 dir" },
  { on = ["g", "p"], run = "cd /mnt/fed/web2/nextLevelPrerequisite", desc = "Go web2 dir" },
  { on = ["g", "i"], run = "cd /mnt/fed/web2/1ts", desc = "Go web2 dir" },
  { on = ["D"], run = "remove", desc = "Trash mama selected files" },
  { on = ["d"], run = "remove --permanently", desc = "Permanently delete selected files" },
]

